# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: HeatHack Sessions - Materials
author: Jean Carletta
logo: ./images/heat_hack_logo1.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: heathack-sessions.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/JeanCarletta/HeatHack-Sessions/  # Online location of your book
 
